### ISSUE TITLE
Empty clusters

### ISSUE THREAD

**Issue by jsl26** [Wedge-lab/dpclust#10]
Hello,

When running dpclust for multiple samples some clusters are not assigned any mutations in the output bed file. 
The colour plots appear to have mutations for all clusters for example 5 clusters but then the output bed file will only assign mutations to clusters 1,3,5. In this example, clusters 2 and 4 will have no mutations assigned and be dropped from the output consensusassignments.bed file and in the mutation_assignment.png file. The contour plots will also show three clones. 
However, the clusters will not be output sequentially as 1,2,3 rather as 1,3,5 so this creates confusion as it may seem like we are missing mutations/clones. 

Could this be looked into?

many thanks,

Joe

**Comment by davidwedge** [comment]
Thanks for raising this Joe, we'll look into it.
