### ISSUE TITLE
Error in dpclust3p

### ISSUE THREAD

**Issue by gevro** [Wedge-lab/dpclust#11]
Hi,
I'm getting this error when running dpclust3p:
```
Error in data.frame(as.character(seqnames(v)), start(ranges(v)), counts_table,  : 
  arguments imply differing number of rows: 5420, 0
Calls: dumpCounts.Sanger -> dumpCountsFromVcf -> formatOutput -> data.frame
```

I think I've traced the bug to this function: dpclust3p:::getCountsTumour. This function is called by dpclust3p:::dumpCountsFromVcf, which in turn is called by dumpCounts.Sanger, in the the example pipeline you give in https://github.com/Wedge-lab/dpclust3p/blob/master/inst/example/preproc_pipeline_caveman.R.

However, your pipeline does not provide any way to change the value of the 'centre' variable which is first used by dumpCountsFromVcf.

Without being able to configure the 'centre' variable in your dpclust3p pipeline, dpclust3p doesn't work. Instead it defaults to centre = 'sanger', which means that this pipeline is only usable by data produced by Sanger pipeline.

Note a similar issue is that refence_genome = "hg19" as default in dumpCountsFromVcf, and dumpCounts.Sanger also does not allow changing that default, which means that the dpclust3p example pipelines do not allow setting to the correct reference genome.

Do you have a pipeline that would allow using dpclust on data that was produced outside of sanger?

Thanks!

**Comment by gevro** [comment]
Hi, I see that the solution is to use dumpCountsFromVcf instead of dumpCounts.Sanger.

I think it might help to have an example pipeline that uses dumpCountsFromVcf, since that is what people with data outside of sanger would need in order to run dpclust.

**Comment by shaghayegh-flower** [comment]
Hi @gevro , I am having the same issue. I think you have been able to fix the issue. Can you please share it with me?

**Comment by gevro** [comment]
Just use dumpCountsFromVcf instead of dumpCounts.Sanger. If you search for that function in the code, you can see the details of how it works.

**Comment by shaghayegh-flower** [comment]
Thanks @gevro, I appreciate your response. Well, that's what I thought and replaced **dumpCounts.Sanger** in preprocessing_pipeline_caveman.R with dumpCountsFromVcf. But I get another warning message that "could not find function "dumpCountsFromVcf". So I thought maybe you actually did something else as well.

**Comment by gevro** [comment]
I don't remember that happening, but I think you can try to find the function in the source code and just load it manually.

**Comment by shaghayegh-flower** [comment]
thank you , yup just digging in to codes now

**Comment by shaghayegh-flower** [comment]
I am actually making some changes from the source code: dumpCountsFromVcf = function(vcf_infile, tumour_outfile, normal_outfile=NA, refence_genome="hs37d5", samplename=NA) {
  dumpCountsFromVcf(vcf_infile, tumour_outfile, normal_outfile=normal_outfile, refence_genome=refence_genome, samplename=samplename)
}
still could not get that working :(

**Comment by gevro** [comment]
I'm sorry I don't remember what I did actually to fix it. Can you give me your e-mail address to connect directly offline?

**Comment by shaghayegh-flower** [comment]
Hi @gevro , thanks. Sure. shaghayegh.soudi@gmail.com
