### ISSUE TITLE
Error in elementLengths(clist) : could not find function "elementLengths"

### ISSUE THREAD

**Issue by gevro** [Wedge-lab/dpclust#12]
Note that the call to elementLengths in the function getAltAllele of the dpclust3p pipeline returns this error with newer versions of R and the S4Vectors package.
```
Error in elementLengths(clist) : could not find function "elementLengths"
```

This is because elementLengths has been deprecated: https://support.bioconductor.org/p/110110/

I think the workaround is to add this line to the dpclust3p preprocessing script:
elementLengths=elementNROWS

**Comment by davidwedge** [comment]
Thanks for pointing this out @gevro. This issue has now been fixed in dpclust3p by replacing the deprecated function elementLengths with elementNROWS.
