### ISSUE TITLE
purity=1 bug

### ISSUE THREAD

**Issue by kamichiotti** [Wedge-lab/dpclust#13]
There is a bug causing a function to divide by 0 when purity is equal to 1. It can be worked around by changing purity=1 to purity=0.999. 

The error generated by this bug is:
```
Error in density.default(c(pi.h.cols[post.burn.in.start - 1, ]), weights = c(wts[post.burn.in.start,  :  non-finite 'to' 
Calls: RunDP ... DirichletProcessClustering -> <Anonymous> -> density -> density.default
Execution halted
```

**Comment by Avramis** [comment]
Hi @kamichiotti . Sorry for the late reply. Would it be possible to provide more details so we can try and replicate the issue?
