### ISSUE TITLE
generate_cluster_ordering on multisamples

### ISSUE THREAD

**Issue by davidwedge** [Wedge-lab/dpclust#15]
generate_cluster_ordering = TRUE causes an error if run on multisample DPClust, as it requires a file that is not generated in multisample runs. The likely fix is that if calc_cluster_order_probs is called in a multisample run it returns a warning but doesn't run.

**Comment by Avramis** [comment]
@MiaoGaoUK could make the suggested edit and test

**Comment by MiaoGaoUK** [comment]
Add a condition in DirichletProcessClustering.R file #459 to stop the code when the parameter is set wrong. Test done.
