### ISSUE TITLE
Issue with !is.na

### ISSUE THREAD

**Issue by rmapbut** [Wedge-lab/dpclust#23]
It looks like in R 4.3.0, running !is.na on a dataframe results in an error now rather than a warning:

Error in if (!is.na(clustering_result$all.assignment.likelihoods)) { : 
  the condition has length > 1

**Comment by Avramis** [comment]
Hello @rmapbut, thank you for bringing the issue to our attention. We will look into it and take the necessary steps to address it.

**Comment by Avramis** [comment]
@christopherwirth Could you please test the code with the commit change in line 138 of the file ./R/SampleMutations.R to return TRUE or FALSE instead of a vector of logical values that can cause the code to break? If everything is correct, please merge the branch into the main.
