### ISSUE TITLE
is.na() only takes one input in R/4.2 and above and cause errors

### ISSUE THREAD

**Issue by Lesky47** [Wedge-lab/dpclust#29]
https://github.com/Wedge-lab/dpclust/blob/d47e3494849c18b3389577458d2c9f6495a6844f/R/DensityEstimator.R#L109
Similar issues raised somewhere else: 
https://github.com/Wedge-lab/dpclust3p/issues/10
https://github.com/Wedge-lab/dpclust3p/issues/14#issuecomment-1668180682

Changing is.na() to all(is.na()) fixed all the issues for me.

**Comment by sdentro** [comment]
This is now fixed in the dev branch, this is now fixed. Many thanks for reporting!
