### ISSUE TITLE
Error in Dockerfile

### ISSUE THREAD

**Issue by rpshep** [Wedge-lab/dpclust#6]
There are 2 double quotes after optparse in the following line in the Docekerfile.

RUN R -q -e 'source("http://bioconductor.org/biocLite.R"); biocLite(c("optparse"","KernSmooth","ks","lattice","ggplot2","gridExtra"))'

**Comment by Avramis** [comment]
Hi @rpshep.Thansk for your observation. We will edit ti accordingly
