### ISSUE TITLE
memory usage issue

### ISSUE THREAD

**Issue by bioinfograd** [Wedge-lab/dpclust#7]
Hello, I have 11 samples from 1 patient so I am trying to run an nd analysis. I ran this successfully on 3 samples but when I increase, when "Estimating density for all MCMC iterations..." the vector being made is gigantic. This is being run on 300 mutations. Is there any way to reduce this or bypass this?  I would love to get the the mutation clusters and CCF of each for each sample for the 1 patient.

Running all 11 samples error message:
Error in array(NA, c(gridsize, length(sampledIters))) : 
  vector is too large
Calls: RunDP ... multiDimensionalClustering -> Gibbs.subclone.density.est.nd -> array

Running all 10 samples error message:
Error: cannot allocate vector of size 13301026.9 Gb

Running all 9 samples error message:
Error: cannot allocate vector of size 738945.9 Gb

Any advise you can give would be greatly appreciated.

**Comment by bioinfograd** [comment]
After going through it more, it would be helpful to add args for resolution and maxburden at the start when running dpclust_pipeline.R.

**Comment by Avramis** [comment]
This issue is, unfortunately, related to memory limitations. We are working on a new version of DP-clust that will be able to handle a larger number of samples and will be more memory-efficient.
